package com.dean.it.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-07-11T11:18:15.135+08:00
 * Generated source version: 3.1.12
 * 
 */
@WebService(targetNamespace = "http://server.it.dean.com/", name = "IHelloService")
@XmlSeeAlso({ObjectFactory.class})
public interface IHelloService {

    @WebResult(name = "customer", targetNamespace = "")
    @RequestWrapper(localName = "selectMaxLongNameStudent", targetNamespace = "http://server.it.dean.com/", className = "com.dean.it.client.SelectMaxLongNameStudent")
    @WebMethod
    @ResponseWrapper(localName = "selectMaxLongNameStudentResponse", targetNamespace = "http://server.it.dean.com/", className = "com.dean.it.client.SelectMaxLongNameStudentResponse")
    public com.dean.it.client.Customer selectMaxLongNameStudent(
        @WebParam(name = "c1", targetNamespace = "")
        com.dean.it.client.Customer c1,
        @WebParam(name = "c2", targetNamespace = "")
        com.dean.it.client.Customer c2
    );

    @WebResult(name = "customer", targetNamespace = "")
    @RequestWrapper(localName = "selectMaxAgeStudent", targetNamespace = "http://server.it.dean.com/", className = "com.dean.it.client.SelectMaxAgeStudent")
    @WebMethod
    @ResponseWrapper(localName = "selectMaxAgeStudentResponse", targetNamespace = "http://server.it.dean.com/", className = "com.dean.it.client.SelectMaxAgeStudentResponse")
    public com.dean.it.client.Customer selectMaxAgeStudent(
        @WebParam(name = "c1", targetNamespace = "")
        com.dean.it.client.Customer c1,
        @WebParam(name = "c2", targetNamespace = "")
        com.dean.it.client.Customer c2
    );
}
